const conversations = {
  refund: { id:'S00005', name:'魏h**', initial:'魏', meta:'3 次服务记录 · 最近进线 09:37', scene:'退款迟迟不到账', order:'6920223542160114724', ticket:'线下打款 · 处理中', emotion:'焦虑 ↑', risk:'关注：历史承诺未完成', riskCopy:'消费者再次进线，建议优先确认退款处理进度', riskType:'attention', summary:'消费者曾有 2 次相关服务记录。上次退款核实尚未完成，本次为再次进线，焦虑情绪正在上升。建议先确认财务工单，再给出明确回访时间。', facts:[['订单状态','退款处理中'],['退款金额','¥8.80'],['原承诺','3 个工作日内完成核实'],['当前责任人','财务组 · G002']], actions:[{icon:'clock-3',title:'催办财务工单',copy:'已等待 2 个工作日，建议今天 18:00 前反馈'}, {icon:'message-circle-more',title:'确认新回访时间',copy:'回复中明确下一次反馈节点，自动加入履约雷达'}], draft:'很抱歉让您再次联系。上次登记的退款核实还没有完成，我已看到对应工单，当前正在财务处理。我先为您加急，并在今天 18:00 前向您回复明确结果。', messages:[['buyer','魏h**','09:37','退款到底去哪了，别踢皮球让我找银行'],['agent','测试客服','09:38','真的很抱歉让您久等了，我先帮您核对之前的处理记录。'],['buyer','魏h**','09:39','上次就说会处理，到现在还没到账'],['agent','测试客服','09:40','我看到上次已经登记了退款核实工单，现在状态还在财务处理。我马上为您催办，今天 18:00 前给您明确结果。']]},
  reaction: { id:'S00015', name:'林a**', initial:'林', meta:'首次进线 · 刚刚', scene:'过敏就医', order:'6920394820174228019', ticket:'不良反应 · 待升级', emotion:'紧急 ↑', risk:'紧急：消费者已就医', riskCopy:'已触发 L3 不良反应流程，需立即升级专员', riskType:'danger', summary:'消费者表示使用面膜后出现红肿刺痛，已在医院，并提出监管投诉。当前缺少产品批次号和门诊资料，建议先完成安全安抚，再创建专项工单。', facts:[['使用商品','测试B5多效修护面膜'],['症状','全脸红肿、刺痛'],['就医状态','已就医'],['风险等级','L3 · 紧急']], actions:[{icon:'shield-alert',title:'升级不良反应专员',copy:'建议 5 分钟内完成分派，限制普通话术'}, {icon:'clipboard-plus',title:'创建专项工单',copy:'已预填症状、订单和就医状态，缺少批次号'}], draft:'很抱歉您现在这么难受，请先遵照医生建议治疗。我们已将您的情况升级给不良反应专员，稍后会有专人跟进。也请您补充产品批次号和门诊资料，我们会尽快协助处理。', messages:[['buyer','林a**','09:41','必须给我个说法！用了你们面膜脸过敏，红肿刺痛，我人现在在医院！'],['buyer','林a**','09:41','资料我可以发，赔偿方案今天给我，不行我就走12315'],['agent','测试客服','09:42','非常抱歉让您遇到这种情况，请先遵照医生建议治疗。我马上为您升级专项专员，资料收到后会第一时间登记处理。']]},
  gift: { id:'S00159', name:'姚b**', initial:'姚', meta:'3 次服务记录 · 最近进线 09:22', scene:'会员权益加赠补发', order:'6920208613936937938', ticket:'补发换货 · 进行中', emotion:'平稳 →', risk:'提醒：补发承诺待履约', riskCopy:'已创建补发工单，48 小时内发出', riskType:'attention', summary:'会员日加赠小样未随包裹发出。客服已确认符合权益并创建补发工单，同时承诺 48 小时内发出。当前等待补发物流单号。', facts:[['权益','会员日加赠精油小样 10ml'],['工单状态','进行中'],['客服承诺','48 小时内发出'],['当前缺口','补发物流单号']], actions:[{icon:'package-check',title:'跟踪补发物流',copy:'工单完成前不要关闭承诺'}, {icon:'bell-ring',title:'设置到期提醒',copy:'剩余 27 小时，提前 4 小时提醒处理人'}], draft:'已为您核实到会员加赠资格，这次是系统没有自动关联赠品。补发工单已经创建，会在 48 小时内发出，单号同步后我会第一时间通知您。', messages:[['buyer','姚b**','09:22','会员日下单的加赠礼怎么没有随包裹发来？'],['agent','测试客服','09:23','亲，核实到您符合会员加赠条件，是系统没有自动关联赠品。'],['agent','测试客服','09:23','这边已经登记补发，48 小时内发出，单号同步后第一时间告诉您。'],['buyer','姚b**','09:24','好的，那麻烦帮我盯一下，别又漏了。']]}
};

let currentKey='refund';
let currentTab='insight';
const $=s=>document.querySelector(s);
const $$=s=>document.querySelectorAll(s);
function toast(message){$('#toast span').textContent=message;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function renderList(){const rows=[['refund','魏h**','退款到底去哪了，别踢皮球让我找银行','09:37','red'],['reaction','林a**','必须给我个说法！我人现在在医院','09:41','red'],['gift','姚b**','会员加赠礼什么时候能发出？','09:22','']];$('#conversationList').innerHTML=rows.map(([key,name,preview,time,risk])=>`<div class="conversation-item ${key===currentKey?'active':''}" data-key="${key}"><div class="avatar-small ${risk?'danger':''}">${name[0]}</div><div class="conversation-copy"><strong>${name}</strong><p>${preview}</p></div><div class="conversation-side"><span>${time}</span>${risk?`<i class="mini-risk ${risk}"></i>`:''}</div></div>`).join('');$$('.conversation-item').forEach(x=>x.addEventListener('click',()=>{currentKey=x.dataset.key;currentTab='insight';renderAll()}))}
function renderChat(){const d=conversations[currentKey];$('#customerAvatar').textContent=d.initial;$('#customerName').innerHTML=`${d.name} <span class="online-dot"></span>`;$('#customerMeta').textContent=d.meta;$('#sceneTag').textContent=d.scene;$('#sessionId').textContent=d.id;$('#orderId').textContent=d.order;$('#ticketId').textContent=d.ticket;$('#emotionTrend').textContent=d.emotion;$('#messageStream').innerHTML=`<div class="date-divider">今天 09:00 之后</div>`+d.messages.map(([role,name,time,text],i)=>`<div class="message ${role}"><div class="message-avatar">${name[0]}</div><div><div class="message-meta"><strong>${name}</strong><time>${time}</time></div><div class="message-bubble ${i===0&&d.riskType==='danger'?'highlight':''}">${text}${role==='buyer'&&d.riskType==='danger'&&i===0?'<div class="attachment"><i data-lucide="file-image"></i>门诊资料.jpg · 待识别</div>':''}</div></div></div>`).join('')}
function riskBanner(){const d=conversations[currentKey];const el=$('#riskBanner');el.classList.toggle('danger',d.riskType==='danger');$('#riskTitle').textContent=d.risk;$('#riskCopy').textContent=d.riskCopy}
function renderCopilot(){const d=conversations[currentKey];const el=$('#copilotContent');if(currentTab==='insight'){el.innerHTML=`<div class="insight-block"><div class="block-head"><h3>当前判断</h3><button>为什么这样判断？</button></div><div class="summary-box">${d.summary}</div></div><div class="insight-block"><div class="block-head"><h3>已核验事实</h3><button>查看证据</button></div><div class="facts-list">${d.facts.map(([a,b])=>`<div class="fact-row"><span>${a}</span><strong class="${a==='风险等级'?'red':''}">${b}</strong></div>`).join('')}</div></div><div class="insight-block"><div class="block-head"><h3>建议动作</h3><button>全部展开</button></div><div class="action-list">${d.actions.map(x=>`<div class="action-item"><i data-lucide="${x.icon}"></i><div><strong>${x.title}</strong><p>${x.copy}</p></div></div>`).join('')}</div></div><div class="insight-block"><div class="block-head"><h3>回复草稿</h3><button>换一种语气</button></div><div class="draft-box"><p>${d.draft}</p><div class="draft-actions"><button class="accept-draft" id="acceptDraft">采纳草稿</button><button class="edit-draft" id="editDraft">编辑</button></div></div></div>`;setTimeout(()=>{$('#acceptDraft')?.addEventListener('click',()=>{$('#composerInput').value=d.draft;toast('草稿已放入输入框')});$('#editDraft')?.addEventListener('click',()=>{$('#composerInput').value=d.draft;$('#composerInput').focus()})})}else if(currentTab==='timeline'){el.innerHTML=`<div class="insight-block"><div class="block-head"><h3>消费者服务时间线</h3><button>展开全部</button></div><div>${[['今天','当前会话 · '+d.scene,'情绪 '+d.emotion,''],['昨天','关联工单 · '+d.ticket,'状态仍在处理中','green'],['5 月 5 日','首次咨询 · 退款 / 售后','已记录处理承诺','green']].map(x=>`<div class="history-event"><i class="history-dot ${x[3]}"></i><div><strong>${x[0]} · ${x[1]}</strong><p>${x[2]}</p></div></div>`).join('')}</div></div><div class="insight-block"><div class="block-head"><h3>关联对象</h3></div><div class="facts-list"><div class="fact-row"><span>订单</span><strong>${d.order}</strong></div><div class="fact-row"><span>工单</span><strong>${d.ticket}</strong></div><div class="fact-row"><span>消费者</span><strong>${d.name}</strong></div></div></div>`}else{el.innerHTML=`<div class="insight-block"><div class="block-head"><h3>可以执行</h3><button>权限说明</button></div><div class="action-list">${d.actions.concat([{icon:'user-round-check',title:'转交组长',copy:'保留当前轨迹、证据和承诺记录'}]).map(x=>`<div class="action-item"><i data-lucide="${x.icon}"></i><div><strong>${x.title}</strong><p>${x.copy}</p><button class="outline-button action-button">预览动作</button></div></div>`).join('')}</div></div>`;$$('.action-button').forEach(x=>x.addEventListener('click',()=>toast('动作预览已生成，请确认后执行')))}lucide.createIcons()}
function renderAll(){renderList();renderChat();riskBanner();renderCopilot();lucide.createIcons()}
function renderPromises(){const rows=[['林a**','专员明天上午电话回访','不良反应 · S00015','今天 12:00','danger','高'],['魏h**','退款核实后 3 个工作日到账','线下打款 · S00005','今天 18:00','overdue','高'],['姚b**','会员加赠 48 小时内发出','补发换货 · S00159','剩余 27 小时','due','中'],['周h**','仓库 24 小时内反馈少件结果','物流异常 · S00006','明天 09:20','due','中'],['邓e**','换货包裹 48 小时内发出','补发换货 · S00001','已履约','done','低']];$('#promiseTable').innerHTML='<div class="promise-row header"><span>消费者</span><span>承诺事项</span><span>关联业务</span><span>截止时间</span><span>状态</span></div>'+rows.map(x=>`<div class="promise-row"><div class="promise-who"><div class="table-avatar">${x[0][0]}</div><strong>${x[0]}</strong></div><div><span class="promise-title">${x[1]}</span><span class="promise-sub">客服已确认</span></div><span class="promise-sub">${x[2]}</span><span class="${x[4]==='overdue'?'table-risk':''}">${x[3]}</span><span class="table-status ${x[4]}">${x[5]}</span></div>`).join('')}
function switchView(view){const cop=$('#copilotView'),rad=$('#radarView');if(view==='radar'){cop.classList.add('hidden');rad.classList.remove('hidden');$$('.rail-button').forEach(x=>x.classList.toggle('active',x.dataset.view==='radar'));renderPromises()}else{rad.classList.add('hidden');cop.classList.remove('hidden');$$('.rail-button').forEach(x=>x.classList.toggle('active',x.dataset.view==='copilot'))}}
document.addEventListener('DOMContentLoaded',()=>{renderAll();$$('[data-view]').forEach(x=>x.addEventListener('click',()=>switchView(x.dataset.view)));$$('.copilot-tab').forEach(x=>x.addEventListener('click',()=>{currentTab=x.dataset.tab;$$('.copilot-tab').forEach(y=>y.classList.toggle('active',y===x));renderCopilot()}));$('#sendButton').addEventListener('click',()=>{if($('#composerInput').value.trim()){toast('消息已发送');$('#composerInput').value=''}});$('#simulateButton').addEventListener('click',()=>toast('已完成一次履约扫描：发现 1 条新增临近到期承诺'));});
